/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: "#4c644e",
        "on-primary": "#ffffff",
        "primary-container": "#8fa98f",
        "on-primary-container": "#273e2a",
        "primary-fixed": "#ceeacd",
        "primary-fixed-dim": "#b3ceb2",
        "on-primary-fixed": "#0a200e",
        "on-primary-fixed-variant": "#354c37",
        "inverse-primary": "#b3ceb2",
        secondary: "#5b6300",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfec60",
        "on-secondary-container": "#616a00",
        "secondary-fixed": "#dfec60",
        "secondary-fixed-dim": "#c2cf47",
        "on-secondary-fixed": "#1a1d00",
        "on-secondary-fixed-variant": "#444b00",
        tertiary: "#506350",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#93a892",
        "on-tertiary-container": "#2b3d2c",
        "tertiary-fixed": "#d3e8d0",
        "tertiary-fixed-dim": "#b7ccb5",
        "on-tertiary-fixed": "#0e1f10",
        "on-tertiary-fixed-variant": "#394b39",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8faf3",
        "on-background": "#191c18",
        surface: "#f8faf3",
        "on-surface": "#191c18",
        "surface-dim": "#d9dbd4",
        "surface-bright": "#f8faf3",
        "surface-variant": "#e1e3dc",
        "on-surface-variant": "#434842",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4ed",
        "surface-container": "#edefe8",
        "surface-container-high": "#e7e9e2",
        "surface-container-highest": "#e1e3dc",
        "inverse-surface": "#2e312d",
        "inverse-on-surface": "#eff2eb",
        "surface-tint": "#4c644e",
        outline: "#737971",
        "outline-variant": "#c3c8bf",
      },
      fontFamily: {
        display: ["Playfair Display", "Noto Serif SC", "serif"],
        body: ["Inter", "Noto Sans SC", "sans-serif"],
        data: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
      },
      spacing: {
        base: "8px",
        "container-max": "1280px",
        "gutter-mobile": "16px",
        "gutter-desktop": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "80px",
      },
      // 注：本刻度为项目自定义上移版，非 Tailwind 默认（默认 lg=0.5rem/xl=0.75rem）。
      // 2xl/3xl 为新增，恢复 xl 之后单调性（旧版 2xl 回落默认值导致 xl>2xl 倒挂）。
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        // full 走 Tailwind 默认 (9999px)
      },
      boxShadow: {
        ambient: "0 20px 40px -15px rgba(51, 51, 51, 0.04)",
        zen: "0 20px 40px -15px rgba(51, 51, 51, 0.04)",
      },
    },
  },
  plugins: [],
};
