/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: "#ab3500",
        "on-primary": "#ffffff",
        "primary-container": "#ff6b35",
        "on-primary-container": "#5f1900",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#832600",
        "inverse-primary": "#ffb59d",
        secondary: "#006e1c",
        "on-secondary": "#ffffff",
        "secondary-container": "#91f78e",
        "on-secondary-container": "#00731e",
        "secondary-fixed": "#94f990",
        "secondary-fixed-dim": "#78dc77",
        "on-secondary-fixed": "#002204",
        "on-secondary-fixed-variant": "#005313",
        tertiary: "#00677e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00a7cb",
        "on-tertiary-container": "#003744",
        "tertiary-fixed": "#b5ebff",
        "tertiary-fixed-dim": "#59d5fb",
        "on-tertiary-fixed": "#001f28",
        "on-tertiary-fixed-variant": "#004e60",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fbf9f8",
        "on-background": "#1b1c1c",
        surface: "#fbf9f8",
        "on-surface": "#1b1c1c",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fbf9f8",
        "surface-variant": "#e4e2e1",
        "on-surface-variant": "#594139",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "surface-tint": "#ab3500",
        outline: "#8d7168",
        "outline-variant": "#e1bfb5",
      },
      fontFamily: {
        display: ["Literata", "Noto Serif SC", "serif"],
        body: ["Plus Jakarta Sans", "Noto Sans SC", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
      },
      spacing: {
        base: "8px",
        "container-max": "1280px",
        "gutter-mobile": "16px",
        "gutter-desktop": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "80px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      boxShadow: {
        ambient: "0 20px 40px -15px rgba(51, 51, 51, 0.04)",
      },
    },
  },
  plugins: [],
};
